// Main page
export const RECEIVE_CONCERTS = 'RECEIVE_CONCERTS'
export const RECEIVE_CONCERTS_ERROR = 'RECEIVE_CONCERTS_ERROR'

export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const RECEIVE_MOVIES_ERROR = 'RECEIVE_MOVIES_ERROR'

export const RECEIVE_RECOMENDED = 'RECEIVE_RECOMENDED'
export const RECEIVE_RECOMENDED_ERROR = 'RECEIVE_RECOMENDED_ERROR'

export const RECEIVE_SUBDIVISIONS = 'RECEIVE_SUBDIVISIONS'

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION'
export const RECEIVE_COORDS = 'RECEIVE_COORDS'

export const SHOW_EVENT_BANNERS = 'SHOW_EVENT_BANNERS'
export const HIDE_EVENT_BANNERS = 'HIDE_EVENT_BANNERS'

export const SHOW_REGISTRATION_MODAL = 'SHOW_REGISTRATION_MODAL'
export const HIDE_REGISTRATION_MODAL = 'HIDE_REGISTRATION_MODAL'

export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM'
export const SHOW_SIGNIN_FORM = 'SHOW_SIGNIN_FORM'

export const RECEIVE_FILTERED_CONTENT = 'RECEIVE_FILTERED_CONTENT'
export const CHANGE_CURRENT_CONTENT = 'CHANGE_CURRENT_CONTENT'

export const CHANGE_CURRENT_DB = 'CHANGE_CURRENT_DB'

// Organizations page
export const RECEIVE_VENUES = 'RECEIVE_VENUES'
export const RECEIVE_HALLS = 'RECEIVE_HALLS'
export const RECEIVE_EVENTS_AND_SHOWS = 'RECEIVE_EVENTS_AND_SHOWS'

// Current event page
export const SAVE_CURRENT_EVENT = 'SAVE_CURRENT_EVENT'
export const RECEIVE_CURRENT_VENUE_EVENTS = 'RECEIVE_CURRENT_VENUE_EVENTS'
export const RECEIVE_CURRENT_EVENT = 'RECEIVE_CURRENT_EVENT'
export const RECEIVE_CURRENT_SHOW = 'RECEIVE_CURRENT_SHOW'
export const RECEIVE_CURRENT_BUILDING = 'RECEIVE_CURRENT_BUILDING'
export const RECEIVE_CURRENT_HALL = 'RECEIVE_CURRENT_HALL'
export const SHOW_WIDGET = 'SHOW_WIDGET'
export const CLOSE_WIDGET = 'CLOSE_WIDGET'

// Tickets
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS'

// Box Offices
export const RECEIVE_BOXOFFICES = 'RECEIVE_BOXOFFICES'

// News
export const RECEIVE_NEWS = 'RECEIVE_NEWS'
export const RECEIVE_NEWS_CATEGORY = 'RECEIVE_NEWS_CATEGORY'

// CART
export const ADD_PLACE_TO_CART = 'ADD_PLACE_TO_CART'
export const ADD_SESSION_ID = 'ADD_SESSION_ID'
export const GET_PLACES_IN_CART = 'GET_PLACES_IN_CART'

// Preloader

export const START_PRELOADER = 'START_PRELOADER'
export const STOP_PRELOADER = 'STOP_PRELOADER'
